Вспомогательные функции
htmlacademy-javascript/1604607-kekstagram-25 pull request #2
Opened 2022-02-21 09:05 UTC by Tuiaara87

2022-02-21 09:40 UTC, ianikitin requested changes

2022-02-21 09:40 UTC, ianikitin commented on js/main.js
> +
Линтер ругается на codestyle. Нужно поправить все его замечания :) 
Хороший пример по стилю кода тут: https://learn.javascript.ru/coding-style

2022-02-21 09:40 UTC, ianikitin commented on js/main.js
> +function getRandomNumber(from, to) {
> Учтите, что диапазон может быть только положительный, включая ноль. А также придумайте, как функция должна вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему.

Нужно добавить проверку по этому условию. Предлагаю выкидывать ошибку если хоть одно условие нарушено.

2022-02-21 09:40 UTC, ianikitin commented on js/main.js
> +  return Math.floor(random)
Можно упростить и возвращать сразу результат. Будет не только лаконичнее, но и избавимся от лишней операции по созданию переменной.

2022-02-21 09:40 UTC, ianikitin commented on js/main.js
> +  return false;
Из задания: 
> // Результат: true, если строка проходит по длине, и false — если не проходит
Кажется, работает наоборот :) 

Хочу предложить идеи по упрощению:
1. Кажется, что присваивание в переменную **lengthLine** лишнее. **.length** стандартный метод строк и он весьма явный для разработчика. 
2. Конструкция **if** в параметре уже принимает условие которое является true или false. Такое же условие нам нужно и вернуть. Как думаешь, как можно упростить? (Подсказка: критерий Д18)

2022-02-21 09:51 UTC, Tuiaara87 commented on js/main.js
> +function getRandomNumber(from, to) {
условие - это "если передать значение «до» меньшее, чем значение «от», или равное ему."?
Как именно выкидывать ошибку?

2022-02-21 09:51 UTC, Tuiaara87 commented on js/main.js
> +  return Math.floor(random)
Мне так понятнее, можно не менять?

2022-02-21 09:52 UTC, Tuiaara87 commented on js/main.js
> +  return Math.floor(random)
Пока хотя бы.. я понимаю, что лучше, когда не повторений итд, но я потом не могу разобрать свой код

2022-02-21 10:01 UTC, ianikitin commented on js/main.js
> +function getRandomNumber(from, to) {
Ага. И проверить, что оба числа больше нуля. 
Что делать при ошибке не регламентируется, можно:
1. Выкинуть именно ошибку через синтаксис [throw new Error](https://learntutorials.net/ru/javascript/topic/268/обработка-ошибок)('<тут можно написать сообщение, которое будет в консоли>')
2. Вывести сообщение в консоль просто через console.error() и прервать выполнение функции.

Примеры обработки ошибок можно посмотреть в этой статье: https://learn.javascript.ru/try-catch На саму конструкцию try...catch пока обращать внимания не стоит)

2022-02-21 10:07 UTC, ianikitin commented on js/main.js
> +  return Math.floor(random)
Ага, давай тогда оставим пока. 
В разработке бывают ситуации, когда в будущем надо что-то доработать/изменить и мы об этом уже знаем. В таких случаях можно оставить комментарий с припиской TODO (многие редакторы такой синтаксис даже подсвечивают, умеют искать все тудушки по проекту и дополнительно с ними работать).
Как пример в нашем случае можно написать так: 

// TODO: упростить return для критерия Д18.

И если останется время -  в будущем вернемся и доделаем.

2022-02-21 10:12 UTC, Tuiaara87 commented on js/main.js
> +  return Math.floor(random)
Безусловно, полезный навык. Я честно, пока не рассматриваю доп.критерии. Мне достаточно пройти правильно все базовые и все. Я просто запутаюсь с концами

2022-02-22 10:25 UTC, ianikitin approved these changes

2022-02-22 10:26 UTC, merged