Отрисуй меня, часть 2. Проверка
htmlacademy-javascript/1604607-kekstagram-25 pull request #6
Opened 2022-03-11 10:24 UTC by Tuiaara87

2022-03-11 11:11 UTC, ianikitin requested changes

2022-03-11 11:11 UTC, ianikitin commented on js/render-thumbnails.js
> +  const closeButton = bigPicture.querySelector('.big-picture__cancel'); // нашла класс, который закрывает модальное окно
Можно вынести вне функции ```renderPopup```, чтобы  не инициализировать и не присваивать переменные каждый раз при вызове функции. Эти данные статичны.

2022-03-11 11:11 UTC, ianikitin commented on js/render-thumbnails.js
> +    document.body.classList.remove('modal-open'); // удалила класс modal-open, чтобы при закрытии попап сранится могла скроллиться
```suggestion
    document.body.classList.remove('modal-open'); // удалила класс modal-open, чтобы при закрытии попапа странится могла скроллиться
```

2022-03-11 11:11 UTC, ianikitin commented on js/render-thumbnails.js
> +  document.addEventListener('keyup', (evt) => {
```suggestion
  });
  
  document.addEventListener('keyup', (evt) => {
```

2022-03-11 11:11 UTC, ianikitin commented on js/render-thumbnails.js
> +  const fragment = document.createDocumentFragment(); //создала коробочку, куда потом все сложу
Предлагаю это вынести в самое начало функции, чтобы сохранить последовательность: 
1. Подготовка контейнера
2. Навешивание доп. обработчиков.
3. Заполнение информацией.

2022-03-11 11:11 UTC, ianikitin commented on js/render-thumbnails.js
> +  socialComments.innerHTML = '';
Что делает эта строка?

2022-03-11 11:11 UTC, ianikitin commented on js/render-thumbnails.js
> +    description.textContent = photo.description; // описание фотографии вставила строкой в блок
У нас получися рассинхрон, возможно когда решали merge conflicts. И структура объекта фотографии немного съехала. Не беда, давай актуализируем)
В data.js в функции createObject нужно возвращать объект по следующей модели: 

```
{
  id: число — идентификатор описания,  // Тут сейчас все правильно
  url: строка — адрес картинки вида photos/{{i}}.jpg // Тут сейчас все правильно
  description: строка — описание фотографии // Тут сейчас все правильно
  likes: число — количество лайков // Тут сейчас все правильно
  comments: { // Вот тут нужно из корня объекта ключи добавить в ключ comments:
    id:  У каждого комментария есть идентификатор — id — случайное число,
    avatar: строка,
    message: одно или два случайных предложения,
    name: случайное имя
  }
}
```

2022-03-11 11:15 UTC, ianikitin commented on js/render-thumbnails.js
> +  document.addEventListener('keyup', (evt) => {
Обязательно нужно проверить, что eventListener удаляется после закрытия окна и не приведет к утечке памяти. 
Если его не удалять, то при каждом вызове функции renderPopup будет создаваться новый слушатель и так, пока память не закончится. На одном примере звучит не страшно и малореалистично, но в больших приложениях это очень даже реально.

2022-03-14 17:17 UTC, ianikitin requested changes

2022-03-14 17:17 UTC, ianikitin commented on js/render-thumbnails.js
> +// socialCommentCount.classList.add('hidden'); // добавила элементу класс hidden, спрятать блоки счётчика комментариев
Закомментированный код нужно убрать, это плохой тон. Если код не нужен - удаляем, если нужен будет в будущем - напишем новый или найдем в истории коммитов)

2022-03-14 17:17 UTC, ianikitin commented on js/render-thumbnails.js
> +commentsLoader.classList.add('hidden'); // добавила элементу класс hidden, спрятать блоки счётчика комментариев
А нужен ли этот класс при старте приложения?

2022-03-14 17:17 UTC, ianikitin commented on js/render-thumbnails.js
> +    // bigPicture.classList.remove('hidden'); // удалила класс hidden у элемента .big-picture, чтобы отобразить блок
Нужно убрать закомментированный код.

2022-03-14 19:16 UTC, Tuiaara87 commented on js/render-thumbnails.js
> +commentsLoader.classList.add('hidden'); // добавила элементу класс hidden, спрятать блоки счётчика комментариев
не нужен. Случайно лишнего добавила

2022-03-14 19:17 UTC, Tuiaara87 commented on js/render-thumbnails.js
> +commentsLoader.classList.add('hidden'); // добавила элементу класс hidden, спрятать блоки счётчика комментариев
Я их просто закомментирую пока

2022-03-15 11:29 UTC, merged