Правда или действие часть 1
htmlacademy-javascript/1604607-kekstagram-25 pull request #7
Opened 2022-03-22 13:34 UTC by Tuiaara87

2022-03-22 14:03 UTC, ianikitin requested changes

2022-03-22 14:03 UTC, ianikitin commented on index.html
> +                  <input class="text" name="hashtags" placeholder="#ХэшТег" required maxlength="20">
Аттрибут `maxlength="20` ограничивает количество символов, которые можно ввести в поле. По ТЗ есть только ограничение в 20 символов на один хэштэг:
> 2.3 максимальная длина одного хэш-тега 20 символов, включая решётку;

2022-03-22 14:03 UTC, ianikitin commented on index.html
> +                  <input class="text" name="hashtags" placeholder="#ХэшТег" required maxlength="20">
> 2.3 хэш-теги необязательны;
Аттрибут required не нужен

2022-03-22 14:03 UTC, ianikitin commented on index.html
> +                  <input class="text" name="hashtags" placeholder="#ХэшТег" required maxlength="20">
Текст перестал быть видимым из-за изменения класса у элемента. Нужно вернуть)

2022-03-22 14:03 UTC, ianikitin commented on js/validation.js
> +
Пустая строка тут не нужна

2022-03-22 14:03 UTC, ianikitin commented on js/validation.js
> +
Пустую строку можно убрать.

2022-03-22 14:03 UTC, ianikitin commented on js/validation.js
> +
Пустая строка не нужна.  Поправь везде, пожалуйста)

2022-03-22 14:03 UTC, ianikitin commented on js/validation.js
> +    errors.push('один и тот же хэш-тег не может быть использован дважды');
Нужно добавить проверку:
> хэш-теги нечувствительны к регистру: #ХэшТег и #хэштег считаются одним и тем же тегом;

2022-03-22 14:03 UTC, ianikitin commented on js/validation.js
> +export { validateHashTag };
Отсутствует проверка на:
> 2.3 хэш-теги разделяются пробелами;

> 2.3 если фокус находится в поле ввода хэш-тега, нажатие на Esc не должно приводить к закрытию формы редактирования изображения.

2022-03-22 14:03 UTC, ianikitin commented on js/validation.js
> +export { validateHashTag };
Если после хэштега поставить пробел, то появляется ошибка. Хотя как таковой ошибки нет. Посмотри, пожалуста, в чем может быть дело. (Возможно, метод [.trim()](https://basicweb.ru/javascript/js_string_trim.php) может помочь)

2022-03-23 12:23 UTC, Tuiaara87 commented on index.html
> +                  <input class="text" name="hashtags" placeholder="#ХэшТег" required maxlength="20">
какого именно класса?

2022-03-23 12:45 UTC, ianikitin commented on index.html
> +                  <input class="text" name="hashtags" placeholder="#ХэшТег" required maxlength="20">
`input`'a, `text__hashtags`

2022-03-23 13:12 UTC, Tuiaara87 commented on js/validation.js
> +export { validateHashTag };
что в условии прописать для 2.3?
 if (hash[0] !== trim() ) {
errors.push('хэш-теги разделяются пробелами ')
}
похоже на правду?

2022-03-23 13:15 UTC, Tuiaara87 commented on js/validation.js
> +export { validateHashTag };
хотя не похоже. Наверное trim()должен быть в теле

2022-03-23 13:15 UTC, ianikitin commented on js/validation.js
> +export { validateHashTag };
А что вернет trim() при сравнении с hash[0]? При валидациях нам нужно не учитывать пробел в начале и в конце строки (тэга). Обрезать их поможет метод trim().

2022-03-23 13:17 UTC, Tuiaara87 commented on js/validation.js
> +    errors.push('один и тот же хэш-тег не может быть использован дважды');
и здесь подскажи как лексически правильно написать в условии, что if (хэш-теги нечувствительны к регистру) { }
особенно фраза "  нечувствительны к регистру"

2022-03-23 14:11 UTC, ianikitin commented on js/validation.js
> +    errors.push('один и тот же хэш-тег не может быть использован дважды');
Удобнее всего привести все к одному регистру [(String.toLowerCase())](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) и сравнить.

2022-03-23 14:13 UTC, ianikitin commented on js/validation.js
> +export { validateHashTag };
> хотя не похоже. Наверное trim()должен быть в теле

Там, где мы делим на элементы массива. Применив метод .trim() к каждому тэгу мы уберем пробелы до и после и они не будут учитываться при валидации.

2022-03-24 13:23 UTC, ianikitin commented on js/validation.js
> +    arrayHashTag[index] = hash.toLowerCase();
Больше не нужно, делаем для `arrayHashTagLowerCased` отдельно.

2022-03-24 13:31 UTC, merged