Помощь друга
htmlacademy-javascript/1604607-kekstagram-25 pull request #9
Opened 2022-04-04 10:13 UTC by Tuiaara87

---
:mortar_board: [Помощь друга](https://up.htmlacademy.ru/javascript/25/user/1604607/tasks/17)

:boom: https://htmlacademy-javascript.github.io/1604607-kekstagram-25/9/

2022-04-04 16:27 UTC, ianikitin requested changes

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +  }
Не везде принимаются корректные значения `value` для фильтров. 
`value` тут у тебя всегда будет число от 0 до 100 (в зависимости от положения слайдера). 
Но value и шаг для каждого фильтра уникальный и описан в ТЗ: 

>Для эффекта «Хром» — filter: grayscale(0..1) с шагом 0.1;
Для эффекта «Сепия» — filter: sepia(0..1) с шагом 0.1;
Для эффекта «Марвин» — filter: invert(0..100%) с шагом 1%;
Для эффекта «Фобос» — filter: blur(0..3px) с шагом 0.1px;
Для эффекта «Зной» — filter: brightness(1..3) с шагом 0.1;
Для эффекта «Оригинал» CSS-стили filter удаляются.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +    },
Можно поменять на стрелочные функции.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +      return value.toFixed(1);
Можно поменять на тернарный оператор.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +  start: 80,
А точно стоит начинать с 80?

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +let currentScaleValue = 100;
При закрытии формы это значение сейчас не сбрасывается и новая фотография открывается в измененном размере.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +let currentFilter = 'none';
При закрытии модального окна фильтры не сбрасываются.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +);
Нужно поправить форматирование.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +  if (currentScaleValue === 25) {
`25` магическое значение, нужно вынести в константу.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +  if (currentScaleValue === 100) {
`100` магическое значение, нужно вынести в константу.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +});
Не выполнен пункт ДЗ:
> Обратите внимание, что при переключении фильтра, уровень эффекта должен сразу сбрасываться до начального состояния, т. е. логика по определению уровня насыщенности должна срабатывать не только при «перемещении» слайдера, но и при переключении фильтров.

2022-04-04 16:27 UTC, ianikitin commented on js/scale.js
> +});
Не выполнен пункт ТЗ:
> При выборе эффекта «Оригинал» слайдер скрывается.

2022-04-05 07:39 UTC, Tuiaara87 commented on js/scale.js
> +  start: 80,
В задании не указано со скольки должно начинаться. Я по демкам указала. С 0 указать?

2022-04-05 07:53 UTC, Tuiaara87 commented on js/scale.js
> +      return value.toFixed(1);
'Number.isInteger(value)?' + value.toFixed(0) : value.toFixed(1)
так пишется?

2022-04-05 08:14 UTC, Tuiaara87 commented on js/scale.js
> +    },
вместо слово funciton указать => ?

2022-04-05 08:16 UTC, Tuiaara87 commented on js/scale.js
> +    },
вернее убрать слово function, потом после value  написать =>? так будет верно?

2022-04-05 08:16 UTC, ianikitin commented on js/scale.js
> +    },
Вот так: [Стрелочные функции](https://learn.javascript.ru/arrow-functions-basics)

2022-04-05 08:17 UTC, ianikitin commented on js/scale.js
> +      return value.toFixed(1);
Так: [Тернарный оператор](https://htmlacademy.ru/blog/boost/frontend/ternary-operator)

2022-04-05 08:18 UTC, ianikitin commented on js/scale.js
> +  start: 80,
Не регламентируется, просто обсудить хотел. Может на 100% сразу фильтр применять по умолчанию. Но на твое усмотрение :)

2022-04-05 08:28 UTC, Tuiaara87 commented on js/scale.js
> +  start: 80,
сделала 20

2022-04-05 09:25 UTC, Tuiaara87 commented on js/scale.js
> +      return value.toFixed(1);
а можно эту конструкцию так оставить (без стрелочной и тернарного оператора)? Я запуталась

2022-04-05 09:25 UTC, Tuiaara87 commented on js/scale.js
> +      return value.toFixed(1);
я по демкам делала

2022-04-07 09:20 UTC, ianikitin requested changes

2022-04-07 09:20 UTC, ianikitin commented on js/scale.js
> +  imgPreview.classList.add('effects__preview--none');
Тут нужно не забыть очистить и применимые стили (с интенсивностью). Сейчас эффекты не сбрасываются при переходе на оригинал.
![Кекстаграм — Яндекс Браузер 2022-04-06 16 37 33](https://user-images.githubusercontent.com/39906730/161987606-3ef85342-ce08-4277-897a-16b7b19287d9.png)

2022-04-07 09:20 UTC, ianikitin commented on js/scale.js
> +
Не выполнен пункт ТЗ:
> При выборе эффекта «Оригинал» слайдер скрывается.

2022-04-07 11:20 UTC, merged